Repository short-d/app, pull requests merged in 2020-01, with the labels that each got.

#48 Add templating engine
  fw/template.go
  modern/mdtemplate/html.go
Labels: enhancement, size/M

#50 Add I/O standard input and standard output definitions
  fw/io.go
Labels: enhancement

#49 Support multiple log levels
  fw/logger.go
  mdtest/logger.go
  modern/mdlogger/local.go
  modern/mdlogger/local_test.go
Labels: size/L

#58 Remove unnecessary code in local logger
  modern/mdlogger/local.go
Labels: enhancement

#59 Add NewGraphQLRequestFake
  mdtest/request.go
  modern/mdrequest/graphql.go
Labels: enhancement

#60 Generalize NewHTTPRequestFake
  mdtest/request.go
  modern/mdrequest/graphql.go
Labels: enhancement

#61 Add LockOSThread to Program Runtime
  fw/runtime.go
  modern/mdruntime/buildin.go
Labels: enhancement

#62 Fixed bug: ProgramRuntimeFake does not implement fw.ProgramRuntime
  mdtest/runtime.go
Labels: bug

#63 Moved event dispatcher implementation from KGS to app
  fw/event.go
  go.mod
  go.sum
  mdtest/runtime.go
  modern/mdevent/dispatcher.go
  modern/mdevent/dispatcher_test.go
Labels: enhancement

#65 Added CI drone targets
  .dockerignore
  .drone.yml
  .gitignore
  Dockerfile-coverage
  Dockerfile-test
Labels: enhancement
