Repository short-d/app, pull requests merged in 2020-05, with the labels that each got.

#87 Fix APIs and add test doubles
  fw/db/connector.go
  fw/env/deployment.go
  fw/graphql/client.go
  fw/graphql/client_fake.go
  fw/graphql/query.go
  fw/logger/entryrepo_fake.go
  fw/logger/logger_fake.go
  fw/metrics/datadog.go
  fw/service/graphql.go
  fw/service/routing.go
  fw/webreq/http.go
Labels: size/L

#88 Fix route handler closure bug
  fw/service/routing.go
Labels: bug, size/XS

#89 Add routing builder
  fw/service/routing.go
Labels: size/S

#90 Fix GraphQL request field and return GraphQL errors to API caller
  fw/graphql/client.go
  fw/graphql/query.go
Labels: size/S

#92 Support adding int flag for CLI
  fw/cli/cobra.go
  fw/cli/flag.go
Labels: size/S

#93 Replace technical details in README with a simple example
  README.md
  doc/cli.png
  doc/example/routing.png
  doc/short.png
  example/routing.go
Labels: documentation

#94 Update example section
  README.md
Labels: size/M

#95 Add example on building GraphQL service
  README.md
  example/graphql/main.go
  example/routing/main.go
  fw/graphql/api.go
  fw/graphql/handler.go
  fw/graphql/validator.go
  fw/service/graphql.go
  fw/service/logger.go
  fw/service/routing.go
Labels: size/L

#96 Add code example for creating gRPC service
  README.md
  example/grpc/main.go
  example/grpc/proto/hello.pb.go
  example/grpc/proto/hello.proto
  example/grpc/scripts/proto
  fw/logger/local.go
  fw/service/grpc.go
  fw/service/logger.go
  go.mod
  go.sum
Labels: size/L

#97 Add API debugging instructions in log message
  fw/service/graphql.go
  fw/service/routing.go
Labels: size/XS

#99 Fix grpc url
  README.md
Labels: size/XS

#100 Fix gRPC client builder interface
  fw/rpc/client.go
Labels: size/XS
