Repository short-d/app, pull requests merged in 2020-04, with the labels that each got.

#69 Support logging to DataDog
  fw/logger.go
  fw/server.go
  mdtest/runtime.go
  modern/mdlogger/datadog.go
  modern/mdlogger/entryrepo.go
  modern/mdlogger/local.go
  modern/mdlogger/local_test.go
  modern/mdlogger/logger.go
  modern/mdlogger/logger_test.go
Labels: size/XXL

#70 Support collecting metrics through DataDog
  fw/context.go
  fw/metrics.go
  modern/mdmetrics/datadog.go
Labels: size/L

#71 Support Analytics through Segment
  fw/analytics.go
  modern/mdanalytics/segment.go
Labels: size/M

#73 Support extracting user's geolocation using IPStack API
  fw/context.go
  fw/geo.go
  modern/mdgeo/ipstack.go
Labels: size/L

#72 Add documentation for DataDog API
  modern/mdlogger/datadog.go
Labels: size/XS

#74 Update Segment to track user's geo location
  modern/mdanalytics/segment.go
Labels: size/S

#75 Fix metrics tags being accidentally concatenated issue
  modern/mdmetrics/datadog.go
Labels: size/XS

#76 Support extracting connection metadata through proxy protocol
  fw/network.go
  go.mod
  go.sum
  modern/mdnetwork/proxy.go
Labels: size/M

#77 Add constructor for Proxy
  modern/mdnetwork/proxy.go
Labels: size/XS

#78 Fix nil pointer for Segment logger
  modern/mdanalytics/segment.go
Labels: size/XS

#79 Add fake metrics and fake analytics
  mdtest/analytics.go
  mdtest/metrics.go
Labels: size/M

#80 Parse configuration from environmental variables
  fw/envconfig.go
  mdtest/env.go
  modern/mdenvconfig/envconfig.go
  modern/mdenvconfig/envconfig_test.go
  unit/unit.go
  unit/unit_test.go
Labels: size/XL

#81 Fix typo
  modern/mdenvconfig/envconfig.go
  modern/mdenvconfig/envconfig_test.go
Labels: size/XS
